### ISSUE TITLE
depend on `python-transforms3d-pip`

### ISSUE THREAD

**Issue by Timple** [DLu/tf_transformations#3]
Thank you for this convenience package!

Instead of install instructions in the readme, why doesn't this package simply list `python-transforms3d-pip` in the `package.xml`?

This means tooling like `rosdep install` can pick it up from there.

**Comment by DLu** [comment]
So I originally took it out in 84167ffd1efaf0a36bcbf57072cbacf7e2351a9f because it [would not be automatically installed as part of the binary](https://answers.ros.org/question/380279/bloom-an-ament_python-package-with-pip-dependencies/), but you are correct in pointing out that it would help rosdep.

**Comment by DLu** [comment]
So, now I remember, that the buildfarm doesn't really play nicely with `pip` dependencies: See [this buildfarm job](https://build.ros2.org/job/Gdev__tf_transformations__ubuntu_focal_amd64/3/console)

```
14:35:22 Identified the following build dependencies (ignoring packages available from source):
14:35:22   - python-numpy
14:35:22   - python-transforms3d-pip
14:35:22 Resolved the dependencies to the following binary packages:
14:35:22   - python-numpy
14:35:22   - transforms3d
14:35:22 Traceback (most recent call last):
14:35:22   File "/usr/lib/python3/dist-packages/apt/cache.py", line 299, in __getitem__
14:35:22     rawpkg = self._cache[key]
14:35:22 KeyError: 'transforms3d'
14:35:22 
14:35:22 During handling of the above exception, another exception occurred:
14:35:22 
14:35:22 Traceback (most recent call last):
14:35:22   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 306, in <module>
14:35:22     main()
14:35:22   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 142, in main
14:35:22     get_binary_package_versions(apt_cache, debian_pkg_names))
14:35:22   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 175, in get_binary_package_versions
14:35:22     pkg = apt_cache[debian_pkg_name]
14:35:22   File "/usr/lib/python3/dist-packages/apt/cache.py", line 301, in __getitem__
14:35:22     raise KeyError('The cache has no package named %r' % key)
14:35:22 KeyError: "The cache has no package named 'transforms3d'"
```

Really what we need is an apt version of `transforms3d` but I haven't had the energy to try to figure out how to do that.

**Comment by ijnek** [comment]
I believe a dependency on ``python3-transforms3d`` is possible now on Jammy after https://github.com/ros/rosdistro/pull/33091 was merged?

**Comment by reinzor** [comment]
@DLu this is resolved now by https://github.com/DLu/tf_transformations/pull/11 , can we get a bloom release for `iron` and `jazzy`? Thanks :)
